#ifndef CATS2_CONNECTION_STATUS_TYPE_HPP
#define CATS2_CONNECTION_STATUS_TYPE_HPP

enum class ConnectionStatus
{
    CONNECTED,
    PENDING,
    DISCONNECTED
};

#endif // CATS2_CONNECTION_STATUS_TYPE_HPP

